[package]
name = "Lemon"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "devnet" }
Monolith = { local = "../monolith" }

[dev-dependencies]
TestHelpers = { local = "../test_helpers" }

[addresses]
lemon = "0x0"