[package]
name = "Juice"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet" }
Monolith = { local = "../monolith" }

[addresses]
juice = "0x0"
